dataset:
  dataset_path: /content/final_train_val_split_augmented/train_val_augmented_no_pad_512
  path_dataset_train_csv: /content/final_train_val_split_augmented/augmented_train.csv
  path_dataset_val_csv: /content/final_train_val_split_augmented/val.csv
  batch_size: 16
model:
  name_pretrained_model: efficientnet_b4
  saving_dir_experiments: results/efficientnet_b4/
  saving_dir_model: models_v2
  num_classes: 1
  num_epoch: 20
  learning_rate: 0.00001
  freeze_layers: 1
  epoch_start_unfreeze: 1
  layer_start_unfreeze: 0
  n_nodes: 256
  dropout: 0.4
  criterion_type: BCE_LOSS
  alpha: 0.70
  pos_class_weight: 2.5
  scheduler_type: CosineAnnealingLR
  lr_patience: 2
  scheduler_step_size: 5
  lr_factor: 0.1
  T_max: 10
  eta_min: 0.0000001
  do_train: 1
  do_test: 1
data:
  size: 380
  do_resize: 1
  normalization: None